WebApplicationResume/Models/Contact.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationResume.Models
{
    public class Contact
    {
        [Key]
        public int id { get; set; }

        [Required]
        [DisplayName("Name of person")]//Displays Name instead of name when validation is required
        public string name { get; set; }

        [Required]
        [DisplayName("Email")]//Displays Name instead of name when validation is required
        public string email { get; set; }

        [Required]
        [DisplayName("Subject title")]//Displays Name instead of name when validation is required
        public string subject { get; set; }

        [Required]
        [DisplayName("Message")]//Displays Name instead of name when validation is required
        public string message { get; set; }

        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

WebApplicationResume/Models/Education.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationResume.Models
{
    public class Education
    {
        [Key]
        public int id { get; set; }

        [Required]
        [DisplayName("Logo of School")]//Displays Name instead of name when validation is required
        public string logo { get; set; }

        [Required]
        [DisplayName("School")]//Displays Name instead of name when validation is required
        public string title { get; set; }

        [Required]
        [DisplayName("School website")]//Displays Name instead of name when validation is required
        public string website { get; set; }

        [Required]
        [DisplayName("GPA")]//Displays Name instead of name when validation is required
        public string gpa { get; set; }

        [Required]
        [DisplayName("City")]//Displays Name instead of name when validation is required
        public string city { get; set; }

        [Required]
        [DisplayName("Diploma")]//Displays Name instead of name when validation is required
        public string diploma { get; set; }

        [Required]
        [DisplayName("Content")]//Displays Name instead of name when validation is required
        public string content { get; set; }



        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

WebApplicationResume/Models/ErrorViewModel.cs
namespace WebApplicationResume.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationResume/Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace WebApplicationResume.Models
{
    public class Project
    {
        [Key]
        public int id { get; set; }

        [Required]
        [DisplayName("Title")]//Displays Name instead of name when validation is required
        public string title { get; set; }


        [Required]
        [DisplayName("Content")]//Displays Name instead of name when validation is required
        public string content { get; set; }

        [Required]
        [DisplayName("Source")]//Displays Name instead of name when validation is required
        public string source { get; set; }

        

        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

WebApplicationResume/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationResume.Data;
using WebApplicationResume.Models;

namespace WebApplicationResume.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AboutMeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Education> objEducationList = _db.Education;
            return View(objEducationList);
        }
    }
}

WebApplicationResume/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationResume.Models;

namespace WebApplicationResume.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationResume/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationResume.Data;
using WebApplicationResume.Models;

namespace WebApplicationResume.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProjectController(ApplicationDbContext db)
        {
            _db = db;
        }
    
        public IActionResult Index()
        {
            IEnumerable<Project> objProjectList = _db.Project;
            return View(objProjectList);
        }
    }
}

WebApplicationResume/Views/AboutMe/Index.cshtml
@model IEnumerable<Education>
@{
    ViewData["Title"] = "Index";
}

<div class="introimg2">
        <div class="introIMAGE2">

        </div>
        <div class="header">
            <h1>About Me</h1>
            <p>Software Engineer</p>

        </div>
        
        <div class="AboutPage">
            <div class="LeftSide">
                <h1>Who am I</h1>
                <p>My name is Ralphilou Tatoy. I have knowledge of front-end and back-end developing concepts. I create software application through agile software development</p>
                <a asp-area="" asp-controller="Contact" asp-action="Index" class="btn btn-primary">Contact</a>
            </div>
            <div class="RightSide">
            <div class="imagecontainer">
                <div class="imagetop">
                    <img src="~/Image/Me.jpg" class="image"/>

                </div>
                <div class="imagebottom">
                    <img src="https://images.unsplash.com/photo-1511367461989-f85a21fda167?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1631&q=80" alt="image" class="image"/>
                </div>
            </div>
        </div>
        </div>
        <div class="cardGrid">
            <h1 class="EducationHeading">School History</h1>
            <div class="cardcontainer1">
        @foreach (var obj in Model)
        {
            
                
                    <div class="cards">
                        <div class="SchoolLogo">
                            <img src="~/Image/@obj.logo"+  alt=@obj.logo/>
                     </div>
                     <a href=@obj.website>
                         @obj.title
                     </a>
                        <p className="GPA">@obj.gpa</p>
                        <p className="City">@obj.city</p>
                    <p className="Diploma">@obj.diploma</p>
                    <p className="AboutSection">@obj.content</p>
                      
                </div>
            
        }
        </div>
            
        </div>
</div>

WebApplicationResume/Views/Contact/Index.cshtml
@model IEnumerable<Contact>
@{
    ViewData["Title"] = "Index";
}

<div class="introimg2">
        <div class="introIMAGE2">

        </div>
        <div class="header">
            <h1>Contact</h1>
			<p> Excited to talk to you!</p>

        </div>
        <div class="col-6 text-end">
            <a asp-controller="Contact" asp-action="Submit" class="btn btn-primary">
                 <i class="bi bi-plus-circle"></i> &nbsp; Create New Category
            </a>
        </div>
</div>

@{
    //client side validation
    //Have to be in cs due to scripts
    //Only server side validation is done when bypass of client side validation
}
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebApplicationResume/Views/Contact/Submit.cshtml
@model Contact
@{
    ViewData["Title"] = "Submit";
}
<partial name="_Notification" />
<head>
    
    
</head>
<form method="post">
            <div class="border p-3 mt-4" id="user">
                <div class="row pb-2">
                    <h2 class="text-primary">Contact Form</h2>
                    <hr />
                </div>
                <div asp-validation-summary="All"></div>
                <div class="mb-3">
                    <label asp-for="name">Name</label>
                    <br />

                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="email">Email</label>
                    <br />

                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="subject">Subject</label>
                    <br />

                    <input asp-for="subject" class="form-control" />
                    <span asp-validation-for="subject" class="text-danger"></span>

                </div>
                <div class="mb-3">
                    <label asp-for="message">Message</label>
                    <br />
                    <textarea rows="6" placeholder="Type your message here" class="form-control" asp-for="message"></textarea>

                    
                    <span asp-validation-for="message" class="text-danger"></span>

                </div>
                <button type="submit" class="btn btn-primary" style="width:150px">Submit</button>

            </div>
        </form>
@{
    //client side validation
    //Have to be in cs due to scripts
    //Only server side validation is done when bypass of client side validation
}
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WebApplicationResume/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="hero1">
        <div class="imageHome">
            <img class="introImage" src="https://images.unsplash.com/photo-1580894740397-0946742deb4b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80" alt="IntroImage" />

        </div>
        <div class="content">
            <p>Software Engineer</p>
            <h1>Developer</h1>
            <div>
                <a class="btn btn-primary" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
            </div>
        </div>
</div>

WebApplicationResume/Views/Project/Index.cshtml
@model IEnumerable<Project>
@{
    ViewData["Title"] = "Index";
}
<partial name="_Header" />
<div class="WorkGrid">
    
    <div class="WorkContainer">
        @foreach(var obj in Model)
        {
            <div class="WorkCard">
                <div class="IMAGE">
                    <img src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Workcardimage" />

                </div>
                <h2 class="WorkTitle">@obj.title</h2>
                <div class="WorkDetails">
                    <p>
                        @obj.content
                    </p>
                    <div class="WorkButtons">
                            <a href=@obj.source class="btn btn-primary">Source</a>
                    </div>
                </div>
            </div>
        }
 </div>
 </div>

WebApplicationResume/Views/Shared/_Header.cshtml
@{
    ViewData["Title"] = "Header";
}

<div class="introimg2">
        <div class="introIMAGE2">

        </div>
        <div class="header">
            <h1>Projects</h1>
            <p>Enjoy</p>

        </div>
</div>

WebApplicationResume/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ralphilou Tatoy</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="~/js/jquery.js"></script>
   
</head>
<body>
    
    <header>
           <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" id="title1">Ralphilou Tatoy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02" style="text-align: center">
                  <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Project" asp-action="Index">
                         Project
                          </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="AboutMe" asp-action="Index">
                         About Me
                          </a>
                    </li>

                        @*<li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                      </div>
                    </li>*@
                  </ul>
                  @*
                      <form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                  </form>
                  *@
                </div>
              </div>
           </nav>

    </header>
    @*<div class="introWeb">
        <p class="introName" id="one">Ralphilou Tatoy</p>
    </div>*@
    <div class="">
        <main role="main">
            @RenderBody()
        </main>
    </div>


    <div class="footers">
        <div class="footerContent">
            <div class="leftSide">
                <div class="home">
                    <h4>
                        <i class="bi bi-house">Van Nuys, CA. 91405</i>
                        
                    </h4>
                </div>
                <div class="email">
                    <i class="bi bi-envelope" style="color:black">ralphilou24@gmail.com</i>
                </div>
            </div>
            <div class="rightSide">
                    <h1>About Me</h1>
                    <img class="Picture" src="~/Image/Me.jpg" alt="PictureOfRalphilou" />
                    <p>My name is Ralphilou Tatoy. I am a first generation that aspire to help and 
                deliver application that improve daily life. 
                Fueled by the hunger of pursuing new knowledge and 
                collaboration.</p>
                <div class="social">
                    <a href="https://github.com/RalphilouT" style="text-decoration: none">
                        <i class="bi bi-github" style="font-size:30px" id="github" ></i>   /   
                    </a>
                    <a href="https://twitter.com/ralphilou1" style="text-decoration: none"> 
                        <i class="bi bi-twitter "style="font-size:30px"></i>   /   
                    </a>
                    <a href="https://www.linkedin.com/in/ralphilou-tatoy-580211149/" style="text-decoration: none"> 
                        <i class="bi bi-linkedin"style="font-size:30px"></i>  
                    </a>
                    
                </div>
                <a class="btn btn-primary align-content-center" asp-area="" asp-controller="Contact" asp-action="Submit">Contact Me</a>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplicationResume/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)//perform temp data to display when action is performed
{
         <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
            toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)//perform temp data to display when action is performed
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
         <script type="text/javascript">
                    toastr.error('@TempData["error"]');
        </script>
}